version: 2
jobs:
    build:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            -   run: make build

    deploy_staging:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on staging server
                  command: HOSTNAME=$STAGING_HOSTNAME PORT=$STAGING_PORT make deploy

    deploy_production:
        machine:
            image: ubuntu-1604:202004-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on production server
                  command: HOSTNAME=$PROD_HOSTNAME PORT=$PROD_PORT make deploy

workflows:
    version: 2
    pull_request:
        jobs:
            - build:
                filters:
                    branches:
                        ignore:
                            - master

    deployment:
        jobs:
            - deploy_staging:
                filters:
                    branches:
                        only: master
            - wait_for_user_approval:
                type: approval
                filters:
                    branches:
                        only: master
                requires:
                    - deploy_staging
            - deploy_production:
                filters:
                    branches:
                        only: master
                requires:
                    - wait_for_user_approval
